### ISSUE TITLE
Posibility for repositories?

### ISSUE THREAD

**Issue by mvee** [sedenion/ovgme#1]
Could it be possible to add http/ftp or similar source as mod repository for easier mod sharing. For example within wing members.

**Comment by sedenion** [comment]
Everything is possible, the question is: does i have the courage and time to do it... 
Low-level TCP Stack/stocket is an unknown terrain for me (but has knowledge about TCP/IP network protocoles), i first have to learn how to handle TCP/IP stockets using C/C++ (never done before), check what tools are available in native under Windows API, and then,  brainstroms about a web interface (its form, its usage, etc...)

**Comment by sedenion** [comment]
done...

**Comment by mvee** [comment]
Whoa! Awesome, that was just what I was looking for.
