### ISSUE TITLE
Please add more than one Mods Profile

### ISSUE THREAD

**Issue by TrakDah** [sedenion/ovgme#11]
Hi

Excellent that someone finally picked up the ball where JSGME left it! Excellent effort.

One thing I do miss a lot in OvGME is the ability to have more than one profile per Mod set. For instance: I may have a game in which I have some selection of mods activate when offline, and another set when online. To be able to switch between the two easily is something I've grown used to from JSGME.

**Comment by TrakDah** [comment]
Just saw you already responded to this before. Well, I've seen your answer. That's fine. See this as a +1

**Comment by sedenion** [comment]
In fact, OvGME is now stable and i will try to implement a multi-profil feature...

**Comment by TrakDah** [comment]
Excellent news, good job!
