### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by Eetsjone** [sedenion/ovgme#12]
Hello,

I have one mod that does not install correct with OVGME. It is a mod that installs the old Lockon music as theme when you select the MiG-21 as menu screen.
When I install the mod I get an error notification and the mod is shown as not-installed. But the files involved are installed. And because of the error notification I cannot use OVGME to un-install the mod.
I have tested with different versions (1.6.6, 1.6.8., 1.6.9 and 1.7.0). Also, the logging is not always updated, sometimes yes, sometimes no.
All other mods I have install without a problem.
 
I have also tested with JSGME and then the mod installed without any error.

Attached is the mod and the logging. I hope you can help me.
[MainMenu_music.zip](https://github.com/sedenion/ovgme/files/785771/MainMenu_music.zip)
[Uploading MainMenu_music.zip…]()
[log.zip](https://github.com/sedenion/ovgme/files/785727/log.zip)

Forget about the second "[Uploading...]" as that did not work.

**Comment by sedenion** [comment]
I think the destination ogg files or folders are in Read-Only... and as i see, the ogg files in your mod is also Read-Only... This Read-Only attribute prevent files to be overwrited or deleted by OvGME.  

Can you confirm please ?

**Comment by Eetsjone** [comment]
Hi Eric,

 

I did check and all files have the same security settings as files in other mods. Also, on the general tab I don’t have the Read Only box tacked for any of the files.

 

Regards,

 

Huub.

 

Van: Eric M. [mailto:notifications@github.com] 
Verzonden: zondag 19 februari 2017 17:24
Aan: sedenion/ovgme <ovgme@noreply.github.com>
CC: Eetsjone <hstheins@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [sedenion/ovgme] Installation failure (#12)

 

I think the destination ogg files or folders are in Read-Only... and as i see, the ogg files in your mod is also Read-Only... This Read-Only attribute prevent files to be overwrited or deleted by OvGME.

Can you confirm please ?

**Comment by Eetsjone** [comment]
Sorry, I forgot in my response, attached you’ll find a mod also for the MiG. This mod will make the turning knobs in the cockpit usable for the mouse wheel so that for example you don’t have to click to select another channel on the radio.

This mod works fine with your programm.

 

Regards,

 

Huub.

 

Van: Eric M. [mailto:notifications@github.com] 
Verzonden: zondag 19 februari 2017 17:24
Aan: sedenion/ovgme <ovgme@noreply.github.com>
CC: Eetsjone <hstheins@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [sedenion/ovgme] Installation failure (#12)

 

I think the destination ogg files or folders are in Read-Only... and as i see, the ogg files in your mod is also Read-Only... This Read-Only attribute prevent files to be overwrited or deleted by OvGME.

Can you confirm please ?

**Comment by sedenion** [comment]
Ok, so this is very strange... i have no idea why this does not work except file or folder acces right. Please try with this zip version: 
[MainMenu_music.zip](https://github.com/sedenion/ovgme/files/786081/MainMenu_music.zip)

**Comment by Eetsjone** [comment]
Thank you Eric, this one works.

Could you please explain what you changed so that I can check it in the future myself?

 

Kind Regards,

 

Huub.

 

Van: Eric M. [mailto:notifications@github.com] 
Verzonden: zondag 19 februari 2017 19:32
Aan: sedenion/ovgme <ovgme@noreply.github.com>
CC: Eetsjone <hstheins@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [sedenion/ovgme] Installation failure (#12)

 

Ok, so this is very strange... i have no idea why this does not work except file or folder acces right. Please try with this zip version:
MainMenu_music.zip <https://github.com/sedenion/ovgme/files/786081/MainMenu_music.zip>

**Comment by sedenion** [comment]
I not changed so much thing... I removed a Read Only flag on one Ogg file, and i "Unblocked" an other one, which was tagged as "Blocked" for an unknown reason: http://superuser.com/questions/590787/what-does-it-mean-when-a-file-is-blocked-in-windows

**Comment by Eetsjone** [comment]
Ok, thanks again for your explanation and help.

 

Kind Regards,

 

Huub.

 

Van: Eric M. [mailto:notifications@github.com] 
Verzonden: maandag 20 februari 2017 18:08
Aan: sedenion/ovgme <ovgme@noreply.github.com>
CC: Eetsjone <hstheins@xs4all.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [sedenion/ovgme] Installation failure (#12)

 

Closed #12 <https://github.com/sedenion/ovgme/issues/12> .
