### ISSUE TITLE
Mod Description text block does not update when navigating mods list with arrow keys

### ISSUE THREAD

**Issue by whartsell** [sedenion/ovgme#13]
when you scroll through the mods list with the up/down arrow keys the mods description: text block does not show the currently highlighted mods description.

Steps to reproduce:
1 add two mod-archives (havent tested this with dir mods but assume its the same)
2 click on the top mod in the list and note its description
3. use the down arrow to scroll to the next mod
    note that the description isnt updated.
4. click on the already highlighted mod
   now the description is updated

it appears you are missing an event listener for when the selected mod changes

**Comment by sedenion** [comment]
I very well understand the problème and i know why this (don't) happen... this is not formelly a bug, this is a "not implemented feature"... I will see that, but no guaranty since WinAPI is sometimes hell to "handle".

**Comment by sedenion** [comment]
problem solved, will be implemented in the next version.
