### ISSUE TITLE
Mods enabled in second game when switching to it while loading profile

### ISSUE THREAD

**Issue by St3v3f26** [sedenion/ovgme#2]
When switching to a game A while loading a mod profile for game B, it will apply mods to game A after you switched

**Comment by sedenion** [comment]
It will even create some strange and unexpected behaviors... (like creating backup for the other game and applying mod to the other one)... I will avoid this kind of behavior by disabling buttons and selection list while installing/uninstall mod process is running... this is the most safely way i found to avoid users "bad behaviors" :D ...

**Comment by sedenion** [comment]
Fixed in dev stage (ready for the next patch)... users now can't do anything but cancel while mods enable / disable is processing. A cancel button was added.
