### ISSUE TITLE
Enhancements to mod profiles

### ISSUE THREAD

**Issue by St3v3f26** [sedenion/ovgme#3]
It is very easy to accidentally overwrite the mod profile because "Apply" and "Save" are just next to each other and no confirmation is required when saving.

Also the possibilty of multiple profiles per game would be neat. Like one profile that passes the IC while the second doesn't.

**Comment by sedenion** [comment]
The ability for multiple profile need new GUI elements (to select and manages profiles)...  maybe in a later release. For now, i will (already done in dev stage) add a confirmation dialog box to confirm profile overwrite or cancel.
