### ISSUE TITLE
OvGME seem case sensitive for copying file in some case (restoring a mod)

### ISSUE THREAD

**Issue by St3v3f26** [sedenion/ovgme#4]
I have a specific mod that creates issues. It some indications in the Black Shark. Everything works fine when it is the only mod activated and deactivated.

But if there are other mods used as well, it will activate the mod just fine. However, when deactivating, it will show an error message about restoring the backup has failed.

It indeed does not create backup files when activating it after another mod in AppData

The problematic mod is here:
https://dl.dropboxusercontent.com/u/58290896/BS%20Cockpit%203%20Alternate_Hud__and__Devrim.ZIP
I'll be happy to help you by providing additional information.

**Comment by sedenion** [comment]
At this stage, i don't know why this happen, and even don't know what exactly happen... This mod seem to have nothing special... I think to debug this kind of thing, i must create some log output (i was lazy to do this, but i think it's now needed).

**Comment by sedenion** [comment]
St3v3f i am not sure, but the issue you spoted with the the specific mod for Black shark, is potentially due to backup corruption when you switched the game while mods was installing (which is, a very bad idea, but i never though of this possibility, so no safeguards to prevent user to do this crazy thing :D ... with the 1.6.1 you now  have to cancel process before doing such things).

What i think you should do:

Restore all mods (uninstall). Uninstall your OvGME version. Repair DCS using the DCS repair. Install OvGME 1.6.1, try again. If the issue still here, copy past me the content of your log file, here or on the ED forum.

**Comment by St3v3f26** [comment]
I've done what you asked. Error is still the same.
Log content:
`ERROR: GME_ModsRestoreMod :: Unable to copy file : C:\Games\DCS World\mods\aircraft\Ka-50\Cockpit\Scripts\SHKVAL\SHKVAL_page.lua
ERROR: GME_ModsRestoreMod :: Unable to copy file : C:\Games\DCS World\mods\aircraft\Ka-50\Cockpit\Scripts\PUI_800\PUI_800_page.lua
ERROR: GME_ModsRestoreMod :: Unable to copy file : C:\Games\DCS World\mods\aircraft\Ka-50\Cockpit\Scripts\materials.lua
ERROR: GME_ModsRestoreMod :: Unable to copy file : C:\Games\DCS World\mods\aircraft\Ka-50\Cockpit\Scripts\HUD\HUD_WEAPON_COMMON_page.lua
ERROR: GME_ModsRestoreMod :: Unable to copy file : C:\Games\DCS World\mods\aircraft\Ka-50\Cockpit\Scripts\HUD\HUD_SHKVAL_page.lua
ERROR: GME_ModsRestoreMod :: Unable to copy file : C:\Games\DCS World\mods\aircraft\Ka-50\Cockpit\Scripts\HUD\HUD_NAV_SPECIPHIC_page.lua
ERROR: GME_ModsRestoreMod :: Unable to copy file : C:\Games\DCS World\mods\aircraft\Ka-50\Cockpit\Scripts\HUD\HUD_NAV_COMMON_page.lua
ERROR: GME_ModsRestoreMod :: Unable to copy file : C:\Games\DCS World\mods\aircraft\Ka-50\Cockpit\Scripts\HUD\HUD_init.lua
ERROR: GME_ModsRestoreMod :: Unable to copy file : C:\Games\DCS World\mods\aircraft\Ka-50\Cockpit\Scripts\EKRAN\Device\EKRAN_localizer.lua
ERROR: GME_ModsRestoreMod :: Unable to copy file : C:\Games\DCS World\mods\aircraft\Ka-50\Cockpit\IndicationTextures\Indication_hud_ka-50.tga
ERROR: GME_ModsRestoreMod :: Unable to copy file : C:\Games\DCS World\mods\aircraft\Ka-50\Cockpit\IndicationTextures\font_Ka-50_SHKVAL.tga`

**Comment by St3v3f26** [comment]
I think I've got the issue narrowed down:
In the mod, the first folder is spelled "mods" while in the game folder it's "Mods"
I changed it to "Mods" and it doesn't seem to cause issues anymore.
So it seems that the folder name being lower case was the problem

**Comment by sedenion** [comment]
Interesting... since when Windows is case sensitive ? Ok, it's a joke, Windows never been case sensitive... so, what happen ?... I will investigate that...

**Comment by St3v3f26** [comment]
Yes, especially because it doesn't cause issues unless there are other mods active

**Comment by sedenion** [comment]
Ok, i think i found where is the problem. The new available build (i updated setup available for 1.6.1 release) should resolve the issue.  So, you desinstall current version, you redownload the 1.6.1 setup, reinstall, and retry with the "lower case" folder... this should now be fixed.

**Comment by St3v3f26** [comment]
Looking good, doesn't seem to cause problems anymore

**Comment by sedenion** [comment]
good, one thing done.
